# Generated by Django 4.0.4 on 2022-06-24 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='facture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('typefact', models.CharField(max_length=100)),
                ('fraiscoms', models.IntegerField()),
            ],
        ),
    ]
